
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: my_cw
  password: <%= ENV["COURSE_WORK_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
development:
  <<: *default
  database: course_work_development

  
test:
  <<: *default
  database: course_work_test

production:
  <<: *default
  database: course_work_production
  username: course_work
  password: <%= ENV["COURSE_WORK_DATABASE_PASSWORD"] %>
